# Setup the taps
tap homebrew-boneyard
tap homebrew-dupes
tap homebrew-games
tap homebrew-versions

# Install the packages
install ack
install ant
install atk
install atomicparsley
install augeas
install autoconf
install autojump
install automake
install awscli
install bagit
install bash
install bison
install boost
install boost-build
install boost149
install brew-gem
install bsdmake
install cabextract
install cairo
install cgdb
install clamav
install cloog
install clucene
install cmake
install contacts
install cpanminus
install crash
install cscope
install ctags
install dnsmasq
install dos2unix
install duplicity
install e2fsprogs
install ec2-ami-tools
install ec2-api-tools
install esniper
install expat
install ext2fuse
install faac
install fairymax
install ffmpeg
install flac
install flvstreamer
install fontconfig
install fontforge
install freetype
install fswatch
install fuse4x
install fuse4x-kext
install gcc
install gd
install gdbm
install gdk-pixbuf
install gettext
install git
install glib
install glibmm
install gmp
install gnu-tar
install gnupg
install gnutls
install gobject-introspection
install gpac
install gpsbabel
install grails
install groovy
install gtk+
install harfbuzz
install howdoi
install htmldoc
install httping
install icu4c
install imagemagick
install intltool
install isl
install jasper
install john-jumbo
install jpeg
install jq
install lame
install lesstif
install libarchive
install libcroco
install libdvdcss
install libebml
install libelf
install libevent
install libffi
install libgcrypt
install libgpg-error
install libgphoto2
install libical
install libicns
install libkml
install libmagic
install libmatroska
install libmpc
install libogg
install libpng
install libpng12
install librsvg
install librsync
install libsigc++
install libspiro
install libtasn1
install libtiff
install libtool
install libusb
install libusb-compat
install libvirt
install libvorbis
install libxml++
install libxml2
install libyaml
install little-cms
install little-cms2
install lzo
install mackup
install macvim
install makedepend
install markdown
install media-info
install mercurial
install mkvtomp4
install mkvtoolnix
install mm-common
install mpfr
install multimarkdown
install namebench
install nettle
install node
install openssl
install osxfuse
install osxutils
install p11-kit
install p7zip
install pandoc
install pango
install pcre
install pdftohtml
install pebble-sdk
install pixman
install pkg-config
install popt
install potrace
install pow
install proctools
install python
install qemu
install qt
install rbenv
install readline
install resty
install rtmpdump
install ruby
install ruby193
install runcocoa
install s3cmd
install sane-backends
install saxon
install speedtest_cli
install sqlite
install ssh-copy-id
install sshfs
install stockfish
install swig
install switchaudio-osx
install terminal-notifier
install texi2html
install texinfo
install the_silver_searcher
install tomcat
install unrar
install vim
install wget
install x264
install xmlformat
install xmlstarlet
install xvid
install xz
install yajl
install yasm
install youtube-dl
install zsh-syntax-highlighting
