vim_plugin_task "peepopen",         "git://github.com/mrchrisadams/vim-peepopen.git"
vim_plugin_task "perl-support",     "git://github.com/benizi/perl-support.vim.git"
vim_plugin_task "a",                "git://github.com/vim-scripts/a.vim.git"
vim_plugin_task "closetag",         "git://github.com/docunext/closetag.vim.git"
vim_plugin_task "tagbar",           "git://github.com/majutsushi/tagbar.git"
