ln -s ~/dotrc/bash_profile ~/.bash_profile
ln -s ~/dotrc/janus/       ~/.janus
ln -s ~/dotrc/janus.rake   ~/.janus.rake
ln -s ~/dotrc/perlcriticrc ~/.perlcriticrc
ln -s ~/dotrc/perltidyrc   ~/.perltidyrc
ln -s ~/dotrc/tmux.conf    ~/.tmux.conf
ln -s ~/dotrc/vimrc        ~/.vimrc
ln -s ~/dotrc/vimrc.before ~/.vimrc.before
ln -s ~/dotrc/zshrc        ~/.zshrc
